config/routes.rb
Rails.application.routes.draw do
  # Static pages
  get "static_pages/home"

  # Devise routes with custom controllers
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  # Posts with comments and likes
  resources :posts do
    resources :comments, only: [:create, :edit, :update, :destroy]
    resources :likes, only: [:create, :destroy]
  end

  # Drawings routes
  resources :drawings do
    collection do
      post 'search_pexels'  # Creates POST /drawings/search_pexels
    end
  end

  # Additional drawing routes
  get "draw", to: "drawings#index"
  post 'drawings/index', to: 'drawings#index'

  # Users resources
  resources :users

  # Root route
  

  scope "(:locale)", locale: /en|es/ do
 root "posts#index"
end

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
  validates :body, presence: true
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post

  def index
    @comments = @post.comments
  end

  def new
    @comment = @post.comments.build
  end

  def create
    @comment = @post.comments.build(comment_params)
    @comment.user = current_user

    respond_to do |format|
      if @comment.save
        format.turbo_stream do
          render turbo_stream: turbo_stream.append(
            "post-#{@post.id}-comments",
            partial: 'comments/comment',
            locals: { comment: @comment }
          )
        end
        format.html { redirect_to @post, notice: "Comment added!" }
      else
        format.turbo_stream do
          render turbo_stream: turbo_stream.replace(
            "new-comment-form",
            partial: 'comments/form',
            locals: { comment: @comment, post: @post }
          )
        end
        format.html { redirect_to @post, alert: "Couldn't save comment" }
      end
    end
  end

  def edit
    @comment = @post.comments.find(params[:id])
  end

  def update
     @comment = @post.comments.find(params[:id])
  
  respond_to do |format|
    if @comment.update(comment_params)
      format.turbo_stream
      format.html { redirect_to @post, notice: 'Comment updated' }
    else
      format.turbo_stream { render :edit }
      format.html { render :edit }
    end
  end
  end

  def destroy
    @comment = current_user.comments.find(params[:id])

    respond_to do |format|
      @comment.destroy
      format.turbo_stream do
        render turbo_stream: turbo_stream.remove("comment-#{@comment.id}")
      end
      format.html { redirect_to @comment.post, notice: "Comment deleted :(" }
    end
  end

  private

  def set_post
    @post = Post.find(params[:post_id])
  end

  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div class="comment" id="comment-<%= comment.id %>">
  <%= turbo_frame_tag "edit-comment-#{comment.id}" do %>
    <div class="comment-user">
      <%= link_to user_path(comment.user), class: "user-info" do %>
        <% if comment.user.image.attached? %>
          <%= image_tag comment.user.image, class: "comment-avatar" %>
        <% else %>
         <%= image_tag 'default-avatar.png', alt: "Default user avatar", class: "comment-avatar" %>
        <% end %>
        <span class="username"><%= comment.user.username %></span>
      <% end %>
      
      <% if comment.user == current_user %>
        <div class="comment-actions">
          <%= link_to edit_post_comment_path(comment.post, comment), 
                      class: "edit-comment" do %>
            <i class="fas fa-edit"></i> Edit
          <% end %>
          
          <%= button_to post_comment_path(comment.post, comment), 
                       method: :delete, 
                       class: "delete-comment",
                       form: { class: "delete-comment-form" } do %>
            <i class="fas fa-trash"></i> Delete
          <% end %>
        </div>
      <% end %>
    </div>
    
    <div class="comment-body">
      <%= simple_format(comment.body) %>
    </div>
  <% end %>
</div>


<style>
.comment {
  padding: 12px 0;
  border-bottom: 1px solid #eee;
}

.comment-user {
  display: flex;
  align-items: center;
  margin-bottom: 8px;
}

.user-info {
  display: flex;
  align-items: center;
  text-decoration: none;
  color: #333;
  flex-grow: 1;
}

.comment-avatar {
  width: 32px;
  height: 32px;
  border-radius: 50%;
  margin-right: 10px;
  object-fit: cover;
}

.username {
  font-weight: 600;
}

.comment-actions {
  display: flex;
  gap: 12px;
}

.edit-comment, .delete-comment {
  background: none;
  border: none;
  color: #666;
  cursor: pointer;
  font-size: 0.9rem;
  display: flex;
  align-items: center;
  gap: 4px;
  padding: 4px 8px;
  border-radius: 4px;
}

.edit-comment:hover {
  color: #1a73e8;
  background: #f0f7ff;
}

.delete-comment {
  color: #f44336;
}

.delete-comment:hover {
  background: #ffebee;
}

.delete-comment-form {
  margin: 0;
}

.comment-body {
  padding-left: 42px; /* Match avatar width + margin */
  color: #333;
  white-space: pre-line;
  line-height: 1.5;
}
</style>

app/views/comments/_form.html.erb
<%= form_with(model: [post, comment], 
              id: dom_id(comment, 'form'),
              class: 'comment-edit-form') do |f| %>
  <%= f.text_area :body, 
                  placeholder: "Write a comment...", 
                  rows: 3,
                  class: 'comment-edit-textarea' %>
  
  <div class="comment-edit-actions">
    <%= f.submit "Post", class: "comment-update-btn" %>
    <%= link_to "Cancel", post_path(post), 
                class: "comment-cancel-btn" %>
  </div>
<% end %>

app/views/comments/create.turbo_stream.erb
<%= turbo_stream.append "post-#{@post.id}-comments" do %>
  <%= render 'comments/comment', comment: @comment %>
<% end %>

<%= turbo_stream.replace "new-comment-form" do %>
  <%= render 'comments/form', comment: Comment.new, post: @post %>
<% end %>

app/views/comments/destroy.turbo_stream.erb
<%= turbo_stream.remove "comment-#{@comment.id}" %>

app/views/comments/edit.html.erb
<%= turbo_frame_tag "edit-comment-#{@comment.id}" do %>
  <div class="editing-comment">
    <%= render 'form', comment: @comment, post: @post %>
  </div>
<% end %>

app/views/comments/update.turbo_stream.erb
<%= turbo_stream.replace "edit-comment-#{@comment.id}" do %>
  <%= render 'comments/comment', comment: @comment %>
<% end %>